version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
    volumes:
      - ./localstack/scripts:/opt/scripts
      - ./localstack:/etc/localstack/init/ready.d
