server:
  servlet:
    context-path: /product-catalog
  port: 8080

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566

security:
  jwt-secret: change-it

events:
  queues:
    catalog-emit: catalog_emit